### ISSUE TITLE
Suggestions are not displayed when the number of suggestions is equal to the limit

### ISSUE THREAD

**Issue by pascal-guislain-cgx** [corejavascript/typeahead.js#189]
When implementing a source as documented with an asyncResults function, e.g.:

    this.customSource = function (userInput, syncResults, asyncResults) {
            source.getFeatures(userInput,
                function (data) {
                    ...
                    var results = transform(data);
                    asyncResults(results);
                }.bind(this),
                function (err) {
                    error(err);
                });
        };

If the limit of suggestions to display is set to N and asyncResults is called with a results array of length N then no suggestions are displayed.

I fixed this issue in my local file by modifying my local copy of typeahead.bundle.js as follows:

	function async(suggestions) {
		suggestions = suggestions || [];
		if (!canceled && rendered < that.limit) {
			that.cancel = $.noop;
			// rendered += suggestions.length; //<- commented
			that._append(query, suggestions.slice(0, that.limit - rendered));
			rendered += suggestions.length; //<-added
			that.async && that.trigger("asyncReceived", query);
		}
	}

Without this change, when suggestions.length is equal to that.limit, no suggestions are appended. I also surmise that the number of suggestions rendered might be wrong otherwise.

**Comment by thewebartisan7** [comment]
I have the same issue.
I have solved by just increasing the limit to 100.
Then on server side I limit the result to 10, by paying attention to not set more than 100.
I think that should not be show all results if database has many data.

Am I missing something?

**Comment by jlbooker** [comment]
What release version of Typeahead are you using? This sounds oddly similar to an old bug that was fixed several releases back.

**Comment by thewebartisan7** [comment]
You are right, I just check and I see mine version is 0.11.1
I will upgrade and check again.

**Comment by thewebartisan7** [comment]
Thanks for info, it works perfectly with version 1.3.1
I was using old one because I didn't notice that package has changed name from typeahead.js to corejs-typeahead in my package.json file so that npm install always installed old one.

**Comment by jlbooker** [comment]
This bug still exists in the official Twitter version (the abandoned repo). In this forked and renamed version, we fixed it some years ago. Thanks anyways for the PR. I'll close this as duplicate now.

**Comment by p-bakker** [comment]
As I commented on the now closed PR: this issue wasn't fixed properly and is still present in the master of this repo.

Can you reopen this case and the PR and consider merging it?
